name: Mi primer workflow

on: [push]

jobs:
  build:
    name: ğŸ—ï¸ Build
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Clonando repositorio
        uses: actions/checkout@v4

      - name: âš™ï¸ Configurando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: ğŸ“¦ Instalando dependencias
        run: npm ci

      - name: ğŸ§± Ejecutando build
        run: npm run build

  compilar:
    name: ğŸ”§ Compilar
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ”§ Compilando app..."

  test:
    name: ğŸ§ª Test
    runs-on: ubuntu-latest
    needs: compilar
    steps:
      - run: echo "ğŸ§ª Ejecutando pruebas..."

  deploy:
    name: ğŸš€ Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "ğŸš€ Deploy listo!"
      - name: If develop branch
        if: github.ref == 'refs/heads/develop'
        run: echo "This is the develop branch!"
      - name: if main branch
        if: github.ref == 'refs/heads/main'
        run: echo $(pwd)
      -  name: RevisiÃ³n de PR
         on: [pull_request]
    jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx prettier --check 